// YouTube AI Video Blocker
// Copyright (c) 2026 Janus Rokkjær
// SPDX-License-Identifier: MIT

const aiKeywords = [
  // Dine oprindelige
  "ai generated", "sora ai", "midjourney", "chatgpt animation",
  "ai art", "ai animation",

  // De mest brugte AI-værktøjer
  "dall-e", "stable diffusion", "runway", "pika labs", 
  "invideo", "pictory", "synthesia", "elevenlabs",
  "openai", "gemini ai", "claude ai", "deepfake",
  "text to video", "ai voice",

  // Typiske formuleringer på AI-klip
  "made with ai", "generated by ai", "created with ai",
  "ai short", "ai film", "ai video"
];

// Hjælpefunktion til at hente kanalnavn
function getChannelName(videoElement) {
  const channelElem = videoElement.querySelector('#channel-name a, #text a, ytd-channel-name a');
  return channelElem ? channelElem.textContent.toLowerCase() : '';
}

function blockAIVideos() {
  // Bredere selectorer – dækker ALT på YouTube nu
  const selectors = [
    'ytd-rich-item-renderer',        // Forside
    'ytd-video-renderer',            // Søgeresultater
    'ytd-compact-video-renderer',    // Sidebar
    'ytd-grid-video-renderer',       // Grid-visning
    'ytd-reel-item-renderer',        // Shorts
    'ytd-rich-grid-media'            // Nyt format
  ];
  
  const videoElements = document.querySelectorAll(selectors.join(', '));
  let blockedCount = 0;

  videoElements.forEach(video => {
    // Hvis den allerede er skjult, spring over
    if (video.style.display === 'none') return;

    const titleElement = video.querySelector('#video-title, #title, [title]');
    let fullText = '';
    let titleText = '';

    if (titleElement) {
      titleText = titleElement.textContent?.toLowerCase() || '';
      const titleAttr = titleElement.getAttribute('title')?.toLowerCase() || '';
      fullText = titleText + ' ' + titleAttr;
    }

    // Hent kanalnavn
    const channelName = getChannelName(video);
    
    // Søg i BÅDE titel OG kanalnavn
    const searchText = fullText + ' ' + channelName;

    const containsAI = aiKeywords.some(keyword => searchText.includes(keyword));

    if (containsAI) {
      // 🔥 INLINE STYLING – ingen CSS-fil nødvendig!
      video.style.display = 'none';
      blockedCount++;
      
      // Vis i konsollen, hvad der blev blokeret (så du kan følge med)
      console.log(`🚫 Blokerede: "${titleText}" (match i titel/kanal)`);
    }
  });

  if (blockedCount > 0) {
    console.log(`🤖 AI Video Blocker: Skjulte ${blockedCount} videoer i denne runde.`);
  }
}

// Kør med det samme
blockAIVideos();

// Overvåg ændringer (scroll, nye videoer) – med debounce for bedre performance
let debounceTimer;
const observer = new MutationObserver(() => {
  clearTimeout(debounceTimer);
  debounceTimer = setTimeout(blockAIVideos, 300);
});

observer.observe(document.body, {
  childList: true,
  subtree: true
});

// Ekstra sikkerhed: Kør hvert 2. sekund i 10 sekunder (fanger langsomt load)
let attempts = 0;
const interval = setInterval(() => {
  blockAIVideos();
  attempts++;
  if (attempts > 5) clearInterval(interval);
}, 2000);

// Reager når YouTube skifter side (uden at genindlæse)
let lastUrl = location.href;
new MutationObserver(() => {
  const url = location.href;
  if (url !== lastUrl) {
    lastUrl = url;
    setTimeout(blockAIVideos, 1000);
  }
}).observe(document, { subtree: true, childList: true });

console.log('✅ YouTube AI Video Blocker er indlæst og aktiv! (Inline styling)');